FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Instalar as dependências do Node.js
RUN npm install

# Copiar o restante da aplicação frontend
COPY . .

# Expor a porta que o Vite usa (padrão é 5173)
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]