services:
  # Serviço do Backend Laravel (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: clickbeard_php_fpm
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
      JWT_SECRET: ${JWT_SECRET}

  # Serviço do Servidor Web Nginx
  nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile.nginx
    container_name: clickbeard_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend

  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: clickbeard_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  # Serviço do Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: clickbeard_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    depends_on:
      - nginx

volumes:
  db_data: